### ISSUE TITLE
NFS Porsche Unleashed Factory Driver mode stage 30/34 car always stuck at N gear

### ISSUE THREAD

**Issue by KyoriAsh** [CookiePLMonster/SilentPatchNFS90s#6]
The Factory Driver mode stage 30/34 where it requires to turn 180 degrees then reverse turn 180 degrees will always stuck at N gear as the stage is required to use manual gear instead of auto gear.

I had tried to remove the `SilentPatchNFS90s.asi` and run the game, and it can shift the gear in manual transmission successfully.

**Comment by CookiePLMonster** [comment]
Provide a save file from before this course.

**Comment by KyoriAsh** [comment]
Here:
[Stucked Factory Driver stage](https://github.com/CookiePLMonster/SilentPatchNFS90s/files/15138327/savedata.zip)

**Comment by YPOC** [comment]
@KyoriAsh For this stage you must shift manually, automatic transmission is disabled intentionally

**Comment by KyoriAsh** [comment]
> @KyoriAsh For this stage you must shift manually, automatic transmission is disabled intentionally

The issue is not manual or auto gear issue, the issue is: You can't shift gear when the Silent Patch is used even in Manual gear mode

Read carefully from my very first post, @YPOC :

> I had tried to remove the `SilentPatchNFS90s.asi` and run the game, and **__it can shift the gear in manual transmission successfully.__**

**Comment by CookiePLMonster** [comment]
I can't reproduce the issue, shifting works fine for me with your save after I remapped controls to match my controller.

SP changes controller enumeration, so it might be that you just need to remap after installing it, and your mappings are for the stock game?

**Comment by KyoriAsh** [comment]
> I can't reproduce the issue, shifting works fine for me with your save after I remapped controls to match my controller.
> 
> SP changes controller enumeration, so it might be that you just need to remap after installing it, and your mappings are for the stock game?

I'm playing using keyboard and I don't have controller, so maybe you might wanted to try on keyboard

**Comment by CookiePLMonster** [comment]
I will try but still do try to bind again, as SP may have invalidated the old mappings.

**Comment by KyoriAsh** [comment]
I try to rebind the shift up and down to another key, but still not working

**Comment by CookiePLMonster** [comment]
OK, I think I see what's up - in the input devices dropdown, your save does not appear to have "Keyboard" selected. While this apparently doesn't matter for basic control inputs, it does matter for the gear changes and I could reproduce your issue. However, opening that dropdown and selecting "Keyboard" specifically allowed me to shift gears properly.

It is possible that my changes to SP shift the order of devices on this list, so what was "Keyboard" for you without SP became something else now.

**Comment by KyoriAsh** [comment]
![image](https://github.com/CookiePLMonster/SilentPatchNFS90s/assets/10785752/dedeccf5-7a72-4b7c-b9d9-b3c206999815)
My "Keyboard" is "鍵盤" but in mojibake in-game

As per your comment, changed to "USB Gaming Keyboard" solved the problem

**Comment by CookiePLMonster** [comment]
Ah, interesting. Gaming peripherals are fun.

Anyways, solved. The game's keyboard mappings behave very weirdly, but are not affected by SP.
